INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: d9cbad93a98764c110b8237b6c436063).
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 93c41314b555ac8846361fa95bb1929f).
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark1329.discord.media
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 694981097934553162 (Guild ID 694981097934553158)
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 3f691e4b80707f20f7811c5a6cbe11da).
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark1329.discord.media
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 694981097934553162 (Guild ID 694981097934553158)
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 05070f036f67740efb0ead13352809bd).
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 9c5e4d630a18f7ce0e3d0ceb441f8c12).
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: def2b5fe5ade090b599ebc2316f7157b).
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: ea530944226ffafdcd531d6dcbbf3f3a).
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: a46e10d65a91a2596f254b2fdcb20cac).
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark1329.discord.media
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 694981097934553162 (Guild ID 694981097934553158)
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 5c093c7073a64965f17bf12de2e43734).
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
WARNING:discord.gateway:Can't keep up, shard ID None websocket is 15.1s behind.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
ERROR:discord.client:Attempting a reconnect in 1.20s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 5c093c7073a64965f17bf12de2e43734.
ERROR:discord.client:Attempting a reconnect in 0.38s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
ERROR:discord.client:Attempting a reconnect in 2.64s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
ERROR:discord.client:Attempting a reconnect in 0.95s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
ERROR:discord.client:Attempting a reconnect in 6.29s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
ERROR:discord.client:Attempting a reconnect in 26.91s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
ERROR:discord.client:Attempting a reconnect in 58.14s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
INFO:discord.gateway:Shard ID None session has been invalidated.
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: d78dcf1a18c0fcb8fbe2615b23528cf5).
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
WARNING:discord.gateway:Can't keep up, shard ID None websocket is 15.2s behind.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
ERROR:discord.client:Attempting a reconnect in 1.10s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Temporary failure in name resolution]
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
WARNING:discord.gateway:Can't keep up, shard ID None websocket is 27.6s behind.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.gateway:Shard ID None has successfully RESUMED session d78dcf1a18c0fcb8fbe2615b23528cf5.
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: f81689e32b2cb35befd523a67436e4b7).
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None has successfully RESUMED session f81689e32b2cb35befd523a67436e4b7.
INFO:discord.gateway:Shard ID None session has been invalidated.
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: a2e1f031a4b3dc41835b110524b80e50).
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
INFO:discord.gateway:Shard ID None has successfully RESUMED session a2e1f031a4b3dc41835b110524b80e50.
ERROR:discord.client:Attempting a reconnect in 0.51s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [Temporary failure in name resolution]
ERROR:discord.client:Attempting a reconnect in 0.56s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [Temporary failure in name resolution]
ERROR:discord.client:Attempting a reconnect in 6.64s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [Temporary failure in name resolution]
ERROR:discord.client:Attempting a reconnect in 9.95s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [Temporary failure in name resolution]
ERROR:discord.client:Attempting a reconnect in 0.32s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [Temporary failure in name resolution]
ERROR:discord.client:Attempting a reconnect in 56.15s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [Temporary failure in name resolution]
ERROR:discord.client:Attempting a reconnect in 73.53s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [Temporary failure in name resolution]
INFO:discord.gateway:Shard ID None session has been invalidated.
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 30ca652d0890f8b983465ac82f60cc2e).
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 30ca652d0890f8b983465ac82f60cc2e.
ERROR:discord.client:Attempting a reconnect in 1.78s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 627, in connect
    await self.ws.poll_event()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 645, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
ERROR:discord.client:Attempting a reconnect in 1.74s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
ERROR:discord.client:Attempting a reconnect in 5.90s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
ERROR:discord.client:Attempting a reconnect in 14.23s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
ERROR:discord.client:Attempting a reconnect in 27.86s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
INFO:discord.gateway:Shard ID None session has been invalidated.
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 83941be788e025bd00ca021eb71a07e2).
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 83941be788e025bd00ca021eb71a07e2.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
ERROR:discord.ext.commands.bot:Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "disconnect" is not found
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 9c57bc11d2c32fba5a48a0989b5b43de).
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
WARNING:discord.gateway:Shard ID None has stopped responding to the gateway. Closing and restarting.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: ad94ddbee41db1318d29af46627df194).
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 511698 has not terminated. Waiting to terminate...
INFO:discord.player:ffmpeg process 511698 should have terminated with a return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 511864 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512004 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512055 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512161 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512223 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512429 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512480 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512531 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512593 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512656 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512796 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512858 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 512920 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513015 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513089 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513262 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513314 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513354 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513427 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513522 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513650 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513781 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513853 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513915 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 513980 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 514042 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 514094 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
INFO:discord.voice_client:Connecting to voice...
INFO:discord.voice_client:Starting voice handshake... (connection attempt 1)
INFO:discord.voice_client:Voice handshake complete. Endpoint found newark7607.discord.media
INFO:discord.player:ffmpeg process 514332 successfully terminated with return code of 0.
INFO:discord.voice_client:The voice handshake is being terminated for Channel ID 1174161405956608121 (Guild ID 891496433881055272)
INFO:discord.voice_client:Disconnecting from voice normally, close code 1000.
ERROR:discord.ext.commands.bot:Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "add" is not found
ERROR:discord.ext.commands.bot:Ignoring exception in command add_clip
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1021, in invoke
    await self.prepare(ctx)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 938, in prepare
    await self._parse_arguments(ctx)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 845, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
  File "/home/matt/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 697, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: name is a required argument that is missing.
ERROR:root:[0;31mERROR:[0m [generic] None: '[url]' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:[url]" ) to search YouTube
INFO:discord.gateway:Shard ID None has successfully RESUMED session ad94ddbee41db1318d29af46627df194.
INFO:discord.gateway:Shard ID None has successfully RESUMED session ad94ddbee41db1318d29af46627df194.
INFO:discord.gateway:Shard ID None has successfully RESUMED session ad94ddbee41db1318d29af46627df194.
INFO:discord.gateway:Shard ID None has successfully RESUMED session ad94ddbee41db1318d29af46627df194.
ERROR:discord.client:Attempting a reconnect in 0.04s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
ERROR:discord.client:Attempting a reconnect in 0.24s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 537, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-d.discord.gg:443 ssl:default [Temporary failure in name resolution]
INFO:discord.gateway:Shard ID None has successfully RESUMED session ad94ddbee41db1318d29af46627df194.
INFO:discord.gateway:Shard ID None has successfully RESUMED session ad94ddbee41db1318d29af46627df194.
INFO:discord.gateway:Shard ID None has successfully RESUMED session ad94ddbee41db1318d29af46627df194.
INFO:discord.gateway:Shard ID None has successfully RESUMED session ad94ddbee41db1318d29af46627df194.
INFO:discord.gateway:Shard ID None has successfully RESUMED session ad94ddbee41db1318d29af46627df194.
ERROR:discord.client:Attempting a reconnect in 0.43s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
ERROR:discord.client:Attempting a reconnect in 2.12s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 537, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
ERROR:discord.client:Attempting a reconnect in 4.00s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 537, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
ERROR:discord.client:Attempting a reconnect in 11.58s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 537, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
INFO:discord.gateway:Shard ID None session has been invalidated.
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 613c271bfccd75187a41deb2e4c6800d).
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
ERROR:discord.client:Attempting a reconnect in 1.74s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 646, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
ERROR:discord.client:Attempting a reconnect in 0.96s
Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.9/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/matt/.local/lib/python3.9/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
  File "/home/matt/.local/lib/python3.9/site-packages/discord/http.py", line 537, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/matt/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-d.discord.gg:443 ssl:default [Name or service not known]
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
INFO:discord.gateway:Shard ID None has successfully RESUMED session 613c271bfccd75187a41deb2e4c6800d.
